//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaderHolder) DeepCopyInto(out *LeaderHolder) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaderHolder.
func (in *LeaderHolder) DeepCopy() *LeaderHolder {
	if in == nil {
		return nil
	}
	out := new(LeaderHolder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaderPolicy) DeepCopyInto(out *LeaderPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaderPolicy.
func (in *LeaderPolicy) DeepCopy() *LeaderPolicy {
	if in == nil {
		return nil
	}
	out := new(LeaderPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LeaderPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaderPolicyList) DeepCopyInto(out *LeaderPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LeaderPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaderPolicyList.
func (in *LeaderPolicyList) DeepCopy() *LeaderPolicyList {
	if in == nil {
		return nil
	}
	out := new(LeaderPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LeaderPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaderPolicySpec) DeepCopyInto(out *LeaderPolicySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaderPolicySpec.
func (in *LeaderPolicySpec) DeepCopy() *LeaderPolicySpec {
	if in == nil {
		return nil
	}
	out := new(LeaderPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaderPolicyStatus) DeepCopyInto(out *LeaderPolicyStatus) {
	*out = *in
	if in.CurrentHolder != nil {
		in, out := &in.CurrentHolder, &out.CurrentHolder
		*out = new(LeaderHolder)
		(*in).DeepCopyInto(*out)
	}
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaderPolicyStatus.
func (in *LeaderPolicyStatus) DeepCopy() *LeaderPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(LeaderPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
