apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-report
  namespace: default
  annotations:
    # Join the leader election pool
    zen-lead/pool: report-generator
    zen-lead/join: "true"
spec:
  schedule: "0 0 * * *"  # Run daily at midnight
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            zen-lead/pool: report-generator
            zen-lead/join: "true"
        spec:
          containers:
          - name: report-generator
            image: report-generator:latest
            # Only the leader pod will execute the job
            # Other pods will be marked as followers

