apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api
        image: my-api:latest
        ports:
        - containerPort: 8443
          name: https  # Named port
---
apiVersion: v1
kind: Service
metadata:
  name: api-server
  annotations:
    zen-lead.io/enabled: "true"
spec:
  selector:
    app: api-server
  ports:
  - port: 443
    targetPort: https  # Named port - zen-lead resolves to 8443
    name: https

